//Delete after integration of consultant-projects.tsx
import type { Project } from "../../projects/types/project.types";
export const mockProjects: Project[] = [
  {
    id: "proj-001",
    name: "FinTech Mobile App Modernization",
    projectName: "FinTech Mobile App Modernization",
    clientName: "Capitec Bank",
    description: "Overhauling legacy iOS and Android mobile applications to improve transaction speeds and UI responsiveness.",
    teamSize: 6,
    allocation: 100,
    startDate: "2026-01-15T00:00:00.000Z",
    endDate: "2026-12-15T00:00:00.000Z",
    status: "IN_PROGRESS",
    addressLine1: "1 Discovery Place",
    city: "Johannesburg",
    province: "Gauteng",
    postalCode: "2196",
    location: {
      addressLine1: "1 Discovery Place",
      addressLine2: "",
      suburb: "Sandton",
      city: "Johannesburg",
      province: "Gauteng",
      postalCode: "2196",
    },
    skills: [
      { id: "skill-01", name: "React Native", competency: "Expert", years: 4, mandatory: true },
      { id: "skill-02", name: "Kotlin", competency: "Intermediate", years: 2, mandatory: false },
    ],
  },
  {
    id: "proj-002",
    name: "AWS Cloud Migration & Infrastructure",
    projectName: "AWS Cloud Migration & Infrastructure",
    clientName: "Discovery Health",
    description: "Migrating core database instances to AWS Aurora and setting up multi-region disaster recovery.",
    teamSize: 4,
    allocation: 50,
    startDate: "2026-03-01T00:00:00.000Z",
    endDate: "2026-08-31T00:00:00.000Z",
    status: "IN_PROGRESS",
    addressLine1: "1 Discovery Place",
    city: "Pretoria",
    province: "Gauteng",
    postalCode: "0157",
    location: {
      addressLine1: "1 Discovery Place",
      addressLine2: "",
      suburb: "Centurion",
      city: "Pretoria",
      province: "Gauteng",
      postalCode: "0157",
    },
    skills: [
      { id: "skill-03", name: "AWS Aurora", competency: "Expert", years: 5, mandatory: true },
      { id: "skill-04", name: "Terraform", competency: "Advanced", years: 3, mandatory: true },
    ],
  },
  {
    id: "proj-003",
    name: "Supply Chain Analytics Dashboard",
    projectName: "Supply Chain Analytics Dashboard",
    clientName: "Shoprite Holdings",
    description: "Building custom real-time analytics dashboards using React, Node.js, and PowerBI integrations.",
    teamSize: 3,
    allocation: 50,
    startDate: "2026-09-01T00:00:00.000Z",
    endDate: "2026-12-31T00:00:00.000Z",
    status: "OPEN",
    addressLine1: "Cnr Old Paarl Rd",
    city: "Cape Town",
    province: "Western Cape",
    postalCode: "7560",
    location: {
      addressLine1: "Cnr Old Paarl Rd",
      addressLine2: "",
      suburb: "Brackenfell",
      city: "Cape Town",
      province: "Western Cape",
      postalCode: "7560",
    },
    skills: [
      { id: "skill-05", name: "React", competency: "Expert", years: 4, mandatory: true },
      { id: "skill-06", name: "Power BI", competency: "Intermediate", years: 2, mandatory: false },
    ],
  },
];