// This file was generated by prisma-field-encryption.
import type { PrismaClient, CvFile } from '@prisma/client'
import {
  ProgressReportCallback,
  defaultProgressReport,
  visitRecords
} from 'prisma-field-encryption/dist/generator/runtime'

type Cursor = CvFile['id']

export async function migrate(
  client: PrismaClient,
  reportProgress: ProgressReportCallback = defaultProgressReport
): Promise<number> {
  return visitRecords<PrismaClient, Cursor>({
    modelName: 'CvFile',
    client,
    getTotalCount: client.cvFile.count,
    migrateRecord,
    reportProgress,
  })
}

async function migrateRecord(client: PrismaClient, cursor: Cursor | undefined) {
  return await client.$transaction(async tx => {
    const record = await tx.cvFile.findFirst({
      take: 1,
      skip: cursor === undefined ? undefined : 1,
      ...(cursor === undefined
        ? {}
        : {
            cursor: {
              id: cursor
            }
          }),
      orderBy: {
        id: 'asc'
      },
      select: {
        id: true,
        rawText: true
      }
    })
    if (!record) {
      return cursor
    }
    await tx.cvFile.update({
      where: {
        id: record.id
      },
      data: {
        rawText: record.rawText
      }
    })
    return record.id
  })
}

/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "rawText": {
 *       "encrypt": true,
 *       "strictDecryption": false
 *     }
 *   },
 *   "connections": {
 *     "consultant": {
 *       "modelName": "Consultant",
 *       "isList": false
 *     },
 *     "user": {
 *       "modelName": "User",
 *       "isList": false
 *     }
 *   }
 * }
 */
